### ISSUE TITLE
How to add python code to the plugin like thing?

### ISSUE THREAD

**Issue by TheInfamousPro** [mine-js/mine.py#1]
I think that this project is a great intiative started by you
But i would like to ask:
     -Is it compatible with 1.5.2(because i am using LAX1Dude's eaglercraft 
     -Is there a specific location where i have to place the file to make it work
Thanks

**Comment by R2turnTrue** [comment]
#### Is is compatible with 1.5.2?
- I didn't test with 1.5.2, but I think it not works with 1.5.2 because of Java 17, api-version specified in plugin.yml (If you use pre-built jar on release), and some event systems

#### Is there a specific location where I have to place the file to make it work?

- Yes. Just place .py files in `plugins/mine-py`

**Comment by TheInfamousPro** [comment]
Thanks!

**Comment by TheInfamousPro** [comment]
![image](https://user-images.githubusercontent.com/96720512/184125441-8297ef48-5417-491a-8e97-5b2019675a3d.png)
does not work rip with 1.5.2

**Comment by TheInfamousPro** [comment]
2022-08-11 11:48:38 [SEVERE] Exception in thread "Thread-6" 
2022-08-11 11:48:38 [SEVERE] org.bukkit.craftbukkit.libs.com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 7
2022-08-11 11:48:38 [SEVERE] 	at org.bukkit.craftbukkit.libs.com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:180)
2022-08-11 11:48:38 [SEVERE] 	at org.bukkit.craftbukkit.libs.com.google.gson.Gson.fromJson(Gson.java:755)
2022-08-11 11:48:38 [SEVERE] 	at org.bukkit.craftbukkit.libs.com.google.gson.Gson.fromJson(Gson.java:694)
2022-08-11 11:48:38 [SEVERE] 	at org.bukkit.craftbukkit.v1_5_R3.updater.BukkitDLUpdaterService.fetchArtifact(BukkitDLUpdaterService.java:51)
2022-08-11 11:48:38 [SEVERE] 	at org.bukkit.craftbukkit.v1_5_R3.updater.BukkitDLUpdaterService.getArtifact(BukkitDLUpdaterService.java:28)
2022-08-11 11:48:38 [SEVERE] 	at org.bukkit.craftbukkit.v1_5_R3.updater.AutoUpdater$1.run(AutoUpdater.java:77)
2022-08-11 11:48:38 [SEVERE] Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 7
2022-08-11 11:48:38 [SEVERE] 	at org.bukkit.craftbukkit.libs.com.google.gson.stream.JsonReader.expect(JsonReader.java:339)
2022-08-11 11:48:38 [SEVERE] 	at org.bukkit.craftbukkit.libs.com.google.gson.stream.JsonReader.beginObject(JsonReader.java:322)
2022-08-11 11:48:38 [SEVERE] 	at org.bukkit.craftbukkit.libs.com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:168)
2022-08-11 11:48:38 [SEVERE] 	... 5 more

^full logs
did i just do something wrong pls help
my plugin replit
https://replit.com/join/foyocmmheb-shihaozhang

**Comment by R2turnTrue** [comment]
I think it's not my plugin's error.

\+ I have no intention of supporting 1.5.2 officially

**Comment by TheInfamousPro** [comment]
i think it is not compatible with the version of the 1.5.2 java
